services:
  # Edge Functions Supabase uniquement
  supabase-functions:
    build:
      context: .
      dockerfile: Dockerfile.functions
    container_name: morocco-host-functions
    ports:
      - "54321:54321"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_DB_URL=${SUPABASE_DB_URL}
      - DENO_ENV=production
      - FUNCTIONS_PORT=54321
    volumes:
      - ./supabase/functions:/home/deno/functions:ro
      - ./supabase/config.toml:/home/deno/config.toml:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:54321/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - morocco-network
    labels:
      - "com.docker.compose.project=morocco-host-helper"
      - "com.docker.compose.service=functions"

networks:
  morocco-network:
    driver: bridge
    name: morocco-host-network
