name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Security audit
        run: npm audit --audit-level=moderate

      - name: Check for secrets in code
        run: |
          if grep -r "VITE_SUPABASE_URL\|VITE_SUPABASE_ANON_KEY\|SUPABASE_" . --exclude-dir=node_modules --exclude-dir=.git; then
            echo "❌ SECURITY WARNING: Potential secrets found in code!"
            exit 1
          fi
          echo "✅ No obvious secrets found in code"
